<?php
/**
 * Created by PhpStorm.
 * User: mohamed
 * Date: 20/09/18
 * Time: 18:54
 */

namespace MegatronicApiBundle\Form;

use MegatronicApiBundle\Document\MegatronicResource;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MegatronicResourceType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('context')
            ->add('type')
            ->add('description')
            ->add('extension')
            ->add('applications')
            ->add('context')
            ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
                'allow_extra_fields' => true,
                'data_class' => MegatronicResource::class,
                'csrf_protection' => false
            ]);
    }

    /**
     * @return null|string
     */
    public function getBlockPrefix()
    {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}
